Add forms
moise-mulungu/My_blog_app pull request #7
Opened 2022-07-14 21:02 UTC by moise-mulungu

On this milestone, I:
- Created a `current_user` method.
- Created forms to perform the following:
  * Create a Post on behalf of the `current_user` method
  * Create a Comment on behalf of the `current_user` method.
- Allowed users to add `likes` to Posts.
- Updated the README file.

2022-07-14 21:22 UTC, ahmetbozaci requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 @moise-mulungu  ✋🏼 

#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.

___ 

### 💯  Nice to have 💯
- Your git-flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
___


### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._
- [ ] Nice to add forms. But you didn't have any method to your controller(post, comment, likes) Kindly add methods to your controller. 
![image](https://user-images.githubusercontent.com/38635158/179087740-e0cb7e9d-0b1d-409c-acea-4cc96bca435c.png)
![image](https://user-images.githubusercontent.com/38635158/179087925-1ec103d6-5c58-498b-8768-31c877964789.png)
![image](https://user-images.githubusercontent.com/38635158/179087938-68f34e2a-0936-4a1f-acc9-71386dd15c72.png)



___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-07-14 21:22 UTC, ahmetbozaci commented on app/views/posts/new.html.erb
> +</div>
- [ ] I can't see the post form on the page. Kindly fix it.

![image](https://user-images.githubusercontent.com/38635158/179086410-14095fec-4d71-4060-81ee-71c192f463db.png)

2022-07-14 21:22 UTC, ahmetbozaci commented on app/views/posts/index.html.erb
> +        <%= Link_to "Add a post", new_user_post_path(@user) %>
- [ ] I am getting error when clicking on any posts. Kindly fix it.

![image](https://user-images.githubusercontent.com/38635158/179086631-67fd51e2-8233-4b1d-b72a-66f68a6edf48.png)

- [ ] Also see all post button giving error too after clicking on it.

![image](https://user-images.githubusercontent.com/38635158/179086755-8bd83ec8-eb40-4303-9ccb-d1295e75ccc3.png)

2022-07-14 21:22 UTC, ahmetbozaci commented on app/views/comments/new.html.erb
> +</div>
- [ ] ı cant reaches this page because of the post error. 

_Next code reviewer, kindly checks if the form working without error or not._

2022-07-15 12:07 UTC, FrederickMih requested changes
Hi @moise-mulungu , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes

- [ ] I can't create a user by running the command `first_user = User.create(name: 'Tom', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.')`. Here is the console error after running the command. This makes it difficult to add a post. Please kindly fix it.

![Screenshot from 2022-07-15 12-55-03](https://user-images.githubusercontent.com/63087491/179219881-ae15e4f3-0e9f-4425-881c-9d0810bfca3b.png)


_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-15 14:27 UTC, FrederickMih commented
- Hi next reviewer, after checking the student codes together with him the app is working well. I discovered that `post_counter` is required when creating a user because he never defaults it to zero in the db. You may consider this field and continue with the review. So the correct command will be first_user = User.create(name: 'Tom', post_counter: 2, photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.'). I have also asked the student to fix it later.

2022-07-15 14:42 UTC, moise-mulungu commented
The reason why this line of code does not work(first_user = User.create(name: 'Tom', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.')) because it missing the posts_counter where it is validated in both user and post models(validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }).
But if you try to add for example the following code by setting the post_counter to 0:
 ```another_user2 = User.create(name: 'Fred', photo: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80', bio: 'Developer from Microverse.', post_counter: 0)```
 this one works.

2022-07-15 14:49 UTC, t-yanick approved these changes
Hi @, 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Great communication with reviewer
:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 16:27 UTC, merged